export interface Options {
  baseUrl?: string;
  rootDir?: string;
  ignore?: string[];
  pattern?: string[];
}

const defaultOptions:Options = {
  baseUrl: process.cwd(),
  rootDir: 'src',
}

export class Bundle {
  DEFAULT_PATTERN = ['**/**.ts', '**/**.tsx', '**/**.js'];
  DEFAULT_IGNORE_PATTERN = [
    '**/**.d.ts',
    '**/logs/**',
    '**/run/**',
    '**/app/extend/**',
    '**/node_modules/**',
    '**/**.test.ts',
    '**/**.test.js',
    '**/__test__/**',
    '*/index.ts',
  ];
  BANNER = '/** This file generated by @autowired/bundle */\n\r';
  constructor(options?: Options) {
    this.init(options);
  }

  /**
   * 初始化
   * @param options 初始化参数
   * @private
   */
  private init(options?: Options){
    options = Object.assign({}, defaultOptions, options);
  }


}